# radio.conf
[Hardware]
# Leave empty or comment out to auto-detect, or provide exact serials
rx_serial = 0000000000000000f77c60dc29417dc3
tx_serial = 000000000000000075b068dc30792007

[RF_Settings]
frequency = 2400000000
# Sample rate in Hz (2e6 = 2000000)
sample_rate = 2000000
# Equivalent to baud_rate
samples_per_symbol = 100
# Gains
tx_gain = 30
rx_gain = 20
# Chunk Size
chunk_size = 2048
capture_seconds = 1.5
timeout = 4
max_resend = 5